export const Questions = [
  {
    prompt: "Who is the president of Indonesia?",
    optionA: "Prabowo",
    optionB: "Jokowi",
    optionC: "Megawati",
    optionD: "Rocky",
    asnwer: "optionB",
  },
  {
    prompt: "Which of this is not a programming language?",
    optionA: "Python",
    optionB: "JavaScript",
    optionC: "Sundanese",
    optionD: "Java",
    asnwer: "optionC",
  },
  {
    prompt: "Which of this is not a javascript framework/library?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
  {
    prompt: "What programming language does flutter use?",
    optionA: "Python",
    optionB: "C++",
    optionC: "PHP",
    optionD: "Dart",
    asnwer: "optionD",
  },
  {
    prompt: "What programming language to use to make ios app?",
    optionA: "Swift",
    optionB: "Golang",
    optionC: "Dart",
    optionD: "Pascal",
    asnwer: "optionA",
  },
];
